name: Deploy on AWS

on:
  push:
    branches: [ master ]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials" Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
      - name: Deploy IaC
        run: aws cloudformation deploy --template-file src/infra/autoscaling_tropo.yaml --stack-name infra-stack
